SAMPLE_CASES = [
    {"owner_login":"jsmith","job_level":"L6","program_team":"Supply Chain",
     "use_case_title":"Demand Forecasting with ML",
     "problem_statement":"Manual demand forecasting is slow and inaccurate.",
     "solution_description":"ML-based time series forecasting pipeline.",
     "ai_technique":"Time Series Forecasting","platform":"Custom","dev_type":"High Code","is_chatbot":"No",
     "tools_services":"Amazon SageMaker, Prophet","key_prompts":"Predict weekly demand for top 500 SKUs",
     "output_outcome":"Automated weekly forecasts with 92% accuracy",
     "time_saved":40.0,"yearly_hc_saved":2.0,"accuracy":92.0,"cost_reduction":15.0,
     "yearly_usd_saved":150000.0,"dev_time_hours":120.0,"status":"In Production",
     "scalability_score":8.5,"innovation_score":7.0},
    {"owner_login":"adoe","job_level":"L5","program_team":"Customer Service",
     "use_case_title":"Automated Ticket Classification",
     "problem_statement":"Support tickets are manually triaged, causing delays.",
     "solution_description":"NLP classifier for auto-routing tickets.",
     "ai_technique":"NLP Text Classification","platform":"Bedrock","dev_type":"Low code","is_chatbot":"Yes",
     "tools_services":"Amazon Comprehend, Lambda","key_prompts":"Classify tickets into 12 categories",
     "output_outcome":"88% accuracy, 60% reduction in triage time",
     "time_saved":60.0,"yearly_hc_saved":5.0,"accuracy":88.0,"cost_reduction":25.0,
     "yearly_usd_saved":500000.0,"dev_time_hours":80.0,"status":"In Production",
     "scalability_score":9.0,"innovation_score":6.5},
    {"owner_login":"bwang","job_level":"L7","program_team":"Operations",
     "use_case_title":"Warehouse Robot Path Optimization",
     "problem_statement":"Warehouse robots follow static paths, causing congestion.",
     "solution_description":"RL agent for dynamic path optimization.",
     "ai_technique":"Reinforcement Learning","platform":"Custom","dev_type":"High Code","is_chatbot":"No",
     "tools_services":"Amazon SageMaker RL, RoboMaker","key_prompts":"Optimize pick paths for 200 robots",
     "output_outcome":"18% improvement in pick throughput",
     "time_saved":18.0,"yearly_hc_saved":1.0,"accuracy":None,"cost_reduction":12.0,
     "yearly_usd_saved":200000.0,"dev_time_hours":200.0,"status":"UAT",
     "scalability_score":7.0,"innovation_score":9.5},
    {"owner_login":"clee","job_level":"L5","program_team":"Marketing",
     "use_case_title":"AI-Generated Product Descriptions",
     "problem_statement":"Writing product descriptions for 10K items/month is a bottleneck.",
     "solution_description":"LLM-based content generation pipeline.",
     "ai_technique":"Generative AI (LLM)","platform":"PartyRock","dev_type":"No code","is_chatbot":"Yes",
     "tools_services":"Amazon Bedrock, Claude","key_prompts":"Generate SEO-optimized descriptions",
     "output_outcome":"80% of products auto-generated, 3x faster",
     "time_saved":70.0,"yearly_hc_saved":8.0,"accuracy":85.0,"cost_reduction":30.0,
     "yearly_usd_saved":800000.0,"dev_time_hours":60.0,"status":"Developing",
     "scalability_score":9.5,"innovation_score":8.0},
    {"owner_login":"dkim","job_level":"L6","program_team":"Finance",
     "use_case_title":"Invoice Anomaly Detection",
     "problem_statement":"Fraudulent invoices slip through manual review.",
     "solution_description":"ML anomaly detection on invoice patterns.",
     "ai_technique":"Anomaly Detection","platform":"Bedrock","dev_type":"Low code","is_chatbot":"No",
     "tools_services":"Amazon SageMaker, XGBoost","key_prompts":"Flag anomalous invoices",
     "output_outcome":"95% anomaly detection, $2M saved annually",
     "time_saved":50.0,"yearly_hc_saved":3.0,"accuracy":95.0,"cost_reduction":40.0,
     "yearly_usd_saved":2000000.0,"dev_time_hours":150.0,"status":"In Production",
     "scalability_score":8.0,"innovation_score":7.5},
]
